# Generated by Django 4.2 on 2024-10-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('consumption', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('check_in_time', models.DateTimeField()),
                ('initial_mileage', models.IntegerField()),
                ('final_milage', models.IntegerField()),
                ('milage', models.IntegerField()),
                ('consumption', models.IntegerField()),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab9.automobile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab9.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab9.automobile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab9.employee')),
            ],
        ),
    ]
