# Generated by Django 5.1.2 on 2024-10-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab9', '0002_waybill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='automobile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lab9.automobile'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='consumption',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='milage',
            field=models.IntegerField(default=None),
        ),
    ]
