# Generated by Django 5.1.2 on 2024-10-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab9', '0003_alter_waybill_automobile_alter_waybill_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
